name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v2

      # Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'

      # Build the application with Gradle
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          chmod +x ./gradlew
          ./gradlew build

      # Log in to Docker Hub (or other Docker registry if required)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/car-rent:latest
